#!/usr/bin/env ruby
# -*- coding: utf-8 -*-

require 'thor'

ROOT = File.dirname(__FILE__)

class Convert < Thor
  desc "slim", "converts and puts slim in www"

  def slim
    `slimrb -p #{ROOT}/src/slim/index.slim > #{ROOT}/www/index.html`
  end

  desc "sass", "converts and puts sass in www"
  def sass
    `sass --update #{ROOT}/src/sass:#{ROOT}/www/stylesheets`
  end

  desc "coffee", "converts and puts coffeescript in www"
  def coffee
    puts 'converting to javascript from coffee script'
    #`coffee -o #{ROOT}/www/javascripts -c #{ROOT}/src/coffee_script/`
  end

  desc "all", "Convert slim, sass and coffee"
  def all
    invoke :slim
    invoke :sass
    invoke :coffee
  end
end

Convert.start
